### ISSUE TITLE
Don't allow SCSI drives to be provisioned as Unit 7

### ISSUE THREAD

**Issue by ajlanghorn** [gds-operations/vcloud-launcher#104]
Unit 7 is typically reserved for the SCSI controller. It isn't selectable when manually creating a drive in vCloud Director, and the API returns an error about `Invalid AddressOnParent value (7) for disk` when you try to do this.

Make sure that if Unit 7 would be used, it is skipped and the addressing process restarts at Unit 8.

**Comment by ajlanghorn** [comment]
This is [documented](https://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc%2FGUID-5872D173-A076-42FE-8D0B-9DB0EB0E7362.html) in the VMware documentation:

> By default, the SCSI controller is assigned to virtual device node (z:7), so that device node is unavailable for hard disks or SCSI devices.

**Comment by deanwilson** [comment]
Issue reviewed on 2016/02/26 and still considered valid.

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this issue. Thank you for your interest and involvement in this project.
