### ISSUE TITLE
Documentation about how to inject scripts when the VM is provisioned.

### ISSUE THREAD

**Issue by fernandohonig** [gds-operations/vcloud-launcher#110]
Hi,

First of all, really good job around these libraries. Thanks!
I am trying to implement them, but wanted to inject a bash script to be run after the vm is provisioned.
I don't understand how it works, or the difference between -p and script_path.
Where the script file is located when the VM is provisioned?.
Thanks!

**Comment by surminus** [comment]
Hi @fernandohonig, 

The best way to do this would be to include this as part of the `vm` configuration options in the config yaml file: 

```
  vm:
    bootstrap:
      script_path: my-script.sh
```

This will end up in `/root/.customization/` and will be run after the machine has been provisioned.

Cheers,
Paul
