### ISSUE TITLE
Bootstrap script_path and script_post_processor are relative to current folder instead of the location of yaml file

### ISSUE THREAD

**Issue by pawilon** [gds-operations/vcloud-launcher#115]
When I define my bootstrap section as following:

```
      bootstrap:
        script_path: 'scripts/bootstrap_preamble.erb'
        script_post_processor: 'scripts/minify_bash.py'
```

vcloud-launcher will look for the scripts in 
- `<current_dir>/scripts/bootstrap_preamble.erb` 
- `<current_dir>/scripts/minify_bash.py` 

I would expect it to instead look in 
- `<location_of_yaml_file>/scripts/bootstrap_preamble.erb` 
- `<location_of_yaml_file>/scripts/minify_bash.py`.

As a workaround I always have to `cd` into the folder containing the yaml file before I run vcloud-launch

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode. Due to this we are unwilling to make a backwards incompatible functional change to address this.
