### ISSUE TITLE
Example preamble script should contain the precustomization and postcustomization sections

### ISSUE THREAD

**Issue by pawilon** [gds-operations/vcloud-launcher#116]
The documentation of this feature: http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1037162

In my opinion this is a somewhat little known feature of the guest customization script, so it would be good for the example preamble in examples/vcloud-launch/basic_preamble.erb to use this structure. 

Script that doesn't define the ifs specified in the docs, will be run both in precustomization and postcustomization, leading to great confusion if the script expects to only be run once.

**Comment by deanwilson** [comment]
We would welcome a PR adding this to the example.
