### ISSUE TITLE
when i run vcloud-launch i get  uninitialized constant Vcloud::Core::Logger

### ISSUE THREAD

**Issue by MartinEtcheverry** [gds-operations/vcloud-launcher#118]
hi , when i run FOG_CREDENTIAL=test_credentials FOG_VCLOUD_TOKEN=imdJ5u835u6WTebggW1f9MPxhxPmhrTWRrQjZPXDvRQ=  vcloud-launch complete.yaml

i get uninitialized constant Vcloud::Core::Logger

my complete.yaml is a copy of one of examples: 
vapps:
  - name: 'vapp-example-complete'
    vdc_name: 'iperf_test'
    catalog_name: 'Catalogo'
    vapp_template_name: 'template'
    vm:
      hardware_config:
        memory: 4096
        cpu: 2
      network_connections:
      - name: 'interna'
        ip_address: '192.168.1.10'

      extra_disks:
      - name: logs-disk
        size: 10240
      - name: data-disk
        size: 20480
      bootstrap:
        script_path: 'scripts/bootstrap_preamble.erb'
        script_post_processor: 'scripts/minify_bash.py'
        vars:
          message: hello world
          role: webserver
          environment: example
      metadata:
        role: webserver
        environment: example
storage_profile: 'Openfiler'

any clue? 
thanks in advance 
Martín

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this issue. Thank you for your interest and involvement in this project.
