### ISSUE TITLE
vcloud-launcher doesn't use DEBUG environment variable

### ISSUE THREAD

**Issue by geriBatai** [gds-operations/vcloud-launcher#58]
README states that you can set DEBUG=true to get full stack traces. However, this is not working:

simas:~/ $ DEBUG=true FOG_RC=fogrc vcloud-launch launch.yml                                                                    
W, [2014-08-05T16:11:20.630412 #45989]  WARN -- : catalog: is deprecated by 'catalog_name'
W, [2014-08-05T16:11:20.630504 #45989]  WARN -- : catalog_item: is deprecated by 'vapp_template_name'
I, [2014-08-05T16:11:20.630542 #45989]  INFO -- : Provisioning vApp XXX.
I, [2014-08-05T16:11:22.608651 #45989]  INFO -- : Instantiating new vApp XXX in vDC 'XXX-vdc'
  vdcInstantiateVapp    100/100  |**************************************************|  0:17
  vappUpdateVm    100/100  |**************************************************|  0:10
  vappUpdateVm    100/100  |**************************************************|  0:11
  vappUpdateVm    100/100  |**************************************************|  0:12
  vappUpdateVm    100/100  |**************************************************|  0:14
undefined method `split' for nil:NilClass
simas:~/ $

**Comment by mattbostock** [comment]
We have raised a PR to fix the documentation: https://github.com/gds-operations/vcloud-launcher/pull/92

The `DEBUG` environment variable is actually read by Fog, so we may have been exposing more to the user than we should. That said, if enough users find `DEBUG` useful, it could be added back. We'd welcome any contributions to that effect.
