### ISSUE TITLE
vCloud Launcher should take multiple files as input

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-launcher#64]
As webops I don't want to use a for loop to use many vapp definition files, I would like to be able to run `vcloud-launch` once:

````
vcloud-launch file-1.yaml file-2.yaml
````
https://www.pivotaltracker.com/story/show/66654822

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
