### ISSUE TITLE
Add stopping machines functionality

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-launcher#65]
Deleting vApps requires them to be stopped. As a user of the tools I would like to be able to do this from the command line or from a script rather than via the UI.

Note: `power_off`, then `undeploy`, is just `stop` in UI (i.e. UI does two things).

https://www.pivotaltracker.com/story/show/69712584

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
