### ISSUE TITLE
Be able to delete machines from the command line

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-launcher#66]
As a user of vCloud Tools, I would like to be able to delete a vApp in a script or from the command line. I would like this to be fully tested, integrated functionality (rather than a utility script).

The interface would be passing the name of a VM to the command.

See https://github.com/gds-operations/vcloud-launcher/issues/65. Deleting requires first stopping.

https://www.pivotaltracker.com/story/show/69709408

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
