### ISSUE TITLE
Support multiple VMs per vApp

### ISSUE THREAD

**Issue by andrewh** [gds-operations/vcloud-launcher#69]
Hello! I'm aware that having a single VM per vApp is preferred (although I can't find anything online about this, only heard it) but some sites (like my current one, Home Office) have already settled on a design that places multiple VMs inside a vApp. Rather than attempt to get a different design in place I'd like to know what the vcloud-tools devs think about the difficulty of adding this support, as it would be a big help to this team and a few others.

**Comment by ajmali2** [comment]
hope everyone had a good break ... has a decision been made whether these features can form part of the vcloud-tools .. or should I build against the branches above instead?  This would be really usefull for the .gov project I am currently working on.

**Comment by andrewh** [comment]
Hi @ajmali2, I'm coming out of a busy period and have been chipping away at this, but can't guarantee a date when it will be ready, sorry!

**Comment by ajmali2** [comment]
Thans Andrew .. i'll keep an eye on this page for any future developments. Good luck

Regards
AJ

**Comment by mig5** [comment]
Just wanted to chime in with a 'me too' - am sysadmin for a large UK project that has the same model as the OP described. Would love to be able to recompose a vApp to add new VMs. I noted that Libcloud also has the same 1:1 approach as vcloud-tools right now too, so am hoping one of you implements it :)

**Comment by JPalmerGithub** [comment]
Just wanted to chime in with a 'me too' too as working for large gov project.

JP

**Comment by andrewh** [comment]
Thanks for the feedback, I will have another look at this.

**Comment by zbuckholz** [comment]
I also look forward to this feature being implemented.

**Comment by pcbadger** [comment]
I've tested AndrewH branches. If you build fog, vcloud-core and vcloud-launcher from them and have only those versions of those gems, it works grand. The only slight snag is that when you build the vapp, it enables vapp fencing by default, which took me a while to work out.

**Comment by andrewh** [comment]
@pcbadger yes that's true, it was a requirement at the time but can be made configurable. How large are the vapps you're creating?

**Comment by pcbadger** [comment]
they're slighty chunky with between 10 and 20 servers each

**Comment by tridlk** [comment]
Hi @andrewh,

I've just stumbled across this, which branches would I need to test this?

https://github.com/andrewh/vcloud-launcher/tree/multiple-vms-per-vapp
https://github.com/andrewh/fog/tree/vcloud-director-compose-vapp
https://github.com/andrewh/vcloud-core/tree/vcloud-director-compose-vapp

**Comment by andrewh** [comment]
@tridik - hi there, yes that's correct.

**Comment by jhughes01** [comment]
Hi,

Is this a development possibility for future? There appears to have been a lot of interest and I too work for a different gov dept. that would benefit highly from vcloud-tools but the single VM per V-APP deployment is a dealbreaker as we have an estabilished estate of ~1000 nodes built using multiple VMs per V-APP.

Thanks

Jackson

**Comment by tlawrence** [comment]
Hi Guys, if there is enough interest in this then the Open Source team here
at UKCloud can take on this work. At the moment our focus is to get multi
VM per vApp support into Terraform though. What would the preference be
amongst this audience?

**Comment by rjw1** [comment]
@tlawrence I think terraform support is more important. The other thing people have talked to me about is VPN support in terraform as well. Our ruby stuff seems to be the only tooling to support it.

**Comment by jhughes01** [comment]
For us the preference would be vcloud-tools however as we're essentially piggybacking off someone elses work I'd be happy to accept that Terraform is more important to others.

However, I was always under the impression that Terraform didn't work inside the UK Cloud space or at least that's the conclusion our tooling team came to (when we had one) and that HMRC were working on a fix.

**Comment by tlawrence** [comment]
@rjw1 We are working on IPSec VPN support for Terraform in the current sprint. This starts with the upstream library though so not sure how quickly we will get in to Terraform main. Would be great if you could raise on http://ideas.ukcloud.com

Also, you could check out https://github.com/ukcloud/ukcloud-vpn for a standalone Gem for IPSec VPN


@jhughes01 as above if you could add your request to ideas.ukcloud.com then we can filter it into the team backlog. 
Are you also aware of the UKCloud Openstack platform? Much greater Terraform support there of course.

**Comment by tlawrence** [comment]
https://twitter.com/CloudAche84/status/842403323445678081/photo/1

**Comment by bobbydeveaux** [comment]
Just the tests to go and then we'll be issuing a pull request into upstream Terraform :)

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this issue. Thank you for your interest and involvement in this project.
