### ISSUE TITLE
Add ability to set disk controller when adding disks

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-launcher#71]
As a WebOps engineer using vCloud Launcher, I would like the ability to specify the disk controller that disks use when provisioning VMs.

This would help prevent recurrence of an issue we had where the disk controller had a known bug and we had to manually modify the BIOS boot order. It would have been easier to specify when creating the machine that we wanted to use a disk controller without the bug.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
