### ISSUE TITLE
Dry-run (simulated) mode

### ISSUE THREAD

**Issue by mattbostock** [gds-operations/vcloud-launcher#94]
As a user of vCloud Launcher
Wishing to see what changes vCloud Launcher would make when run
I would like vCloud Launcher to have a 'dry-run' mode

There is [prior art](https://github.com/gds-operations/vcloud-edge_gateway/blob/c6ed37a957d634021db92e621ea3f792461a2518/lib/vcloud/edge_gateway/cli.rb#L16) for this in the vCloud Edge Gateway gem.

**Comment by surminus** [comment]
Added in https://github.com/gds-operations/vcloud-launcher/pull/114
