### ISSUE TITLE
Syntax checking

### ISSUE THREAD

**Issue by mattbostock** [gds-operations/vcloud-launcher#95]
As a user of vCloud Launcher

I would like to be able to syntax-check my vCloud Launcher YAML configuration file

So that I can run continuous integration tests against my configuration

To ensure that the syntax is correct before I provision new machines in a Production environment within tight time constraints

**Comment by rjw1** [comment]
@timmow and i did some work on this. https://github.com/timmow/vcloud-launcher/commit/1cf49837797da8c9ad44cd016ca68b29cabc1990

**Comment by timmow** [comment]
And now not in the fork 1cf49837797da8c9ad44cd016ca68b29cabc1990

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this issue. Thank you for your interest and involvement in this project.
